services:
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: db
      POSTGRES_PASSWORD: mysecretpassword

  backend:
    build: .
    restart: always
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:mysecretpassword@db:5432/postgres
