"""moedas added

Revision ID: 71e3ca21074b
Revises: 294c91e63a6e
Create Date: 2024-11-28 16:49:33.090488

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71e3ca21074b'
down_revision: Union[str, None] = '294c91e63a6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aluno', sa.Column('moedas', sa.Float(), nullable=False))
    op.add_column('professor', sa.Column('moedas', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('professor', 'moedas')
    op.drop_column('aluno', 'moedas')
    # ### end Alembic commands ###
