"""create aluno's table

Revision ID: 90f05c737fee
Revises:
Create Date: 2024-10-26 01:28:17.386001

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "90f05c737fee"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "aluno",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("nome", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("cpf", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("rg", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("endereco", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "instituicao_ensino", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("curso", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_aluno_cpf"), "aluno", ["cpf"], unique=False)
    op.create_index(op.f("ix_aluno_email"), "aluno", ["email"], unique=False)
    op.create_index(op.f("ix_aluno_endereco"), "aluno", ["endereco"], unique=False)
    op.create_index(op.f("ix_aluno_nome"), "aluno", ["nome"], unique=False)
    op.create_index(op.f("ix_aluno_rg"), "aluno", ["rg"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_aluno_rg"), table_name="aluno")
    op.drop_index(op.f("ix_aluno_nome"), table_name="aluno")
    op.drop_index(op.f("ix_aluno_endereco"), table_name="aluno")
    op.drop_index(op.f("ix_aluno_email"), table_name="aluno")
    op.drop_index(op.f("ix_aluno_cpf"), table_name="aluno")
    op.drop_table("aluno")
    # ### end Alembic commands ###
